markdown: kramdown
rouge: true
safe: false
permalink: /posts/:title.html
exclude:
  - README.md
  - nodejs

host: wkliang.github.com

custom:
    category:
        note: 筆記
        reading: 閱讀
        thinking: 思考
        programming: 程式
    categories:
      - name:  note
        title: 筆記

      - name:  reading
        title: 閱讀

      - name:  thinking
        title: 思考

      - name:  programming
        title: 程式

meta:
    authors:
      - name: wkliang
        email: wenkui.liang@gmail.com
        gravatar: none

    gravatar:
        base: http://www.gravatar.com/avatar/
        param: ?s=
